### ISSUE TITLE
Images doesn't display on GitHub pages

### ISSUE THREAD

**Issue by divyashukla23** [divyashukla23/KFC-Clone#2]
link:https://divyashukla23.github.io/KFC-Clone/KFC%20Clone/index.html#
Issue: Some images (footer & header logos) are broken while we load it with GitHub pages:
![image](https://user-images.githubusercontent.com/70107635/122649826-71640780-d14d-11eb-89d8-4aa411025d53.png)
However the same code works fine on local.
![image](https://user-images.githubusercontent.com/70107635/122649879-b7b96680-d14d-11eb-9bf8-447864a893d0.png)

**Comment by ahcodes** [comment]
Hi Divya, I could try and see what's going wrong here. Would you mind assigning me for this issue? Thanks!

**Comment by divyashukla23** [comment]
Sure

**Comment by purry03** [comment]
I haven't checked the code yet , but make sure that the filenames used in the `src` tag have identical case as the filename. The reason is works on local is that windows ignores case when looking for the files but Linux doesn't ( which is most probably what GitHub) uses to host GitHub pages.

**Comment by ahcodes** [comment]
@purry03 Yeah, there was indeed a small typo where the path of the image was written in the source as `.../KFC Clone/asset... `instead of `.../KFC Clone/Asset...`.

**Comment by purry03** [comment]
> @purry03 Yeah, there was indeed a small typo where the path of the image was written in the source as `.../KFC Clone/asset... `instead of `.../KFC Clone/Asset...`.

Yep. Although I still find the image paths really weird. They need to use relative file paths.

For Example:
`src="/[repo]/KFC Clone/Assets/images/logo.png"`
needs to be changed to
`src="Assets/images/logo.png"`

I'm making a PR with the fixed image paths atm.

**Comment by divyashukla23** [comment]
I have tried that too, i dont think it works but lets try

**Comment by divyashukla23** [comment]
Its done Thanks @ahcodes @purry03 @Drv24

**Comment by ahcodes** [comment]
Ahh darn it, @purry03 you beat me to it! Better luck next time for me :smile:
